version: '3.8'

services:
  app:
    build:
      context: ./slm2025
      dockerfile: ../Dockerfile
    container_name: slm2025_apache
    volumes:
      - ./slm2025:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    extra_hosts:
      - "host.docker.internal:host-gateway" # permite conectar con BD local (XAMPP)
    restart: unless-stopped

